### ISSUE TITLE
Fix nodejs sdk tests

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-node-sdk-js#73] opened 2022-07-07 09:34 UTC
**Task description**

Currently the tests fail in nodejs SDK on both the old testnet and the new

**Comment by orhoj** [comment] 2022-08-08 07:00
Closing this as it is a duplicate of https://github.com/Concordium/concordium-node-sdk-js/issues/32.

**Closed by orhoj** 2022-08-08 07:00 UTC
Labels: [Type] Task
