### ISSUE TITLE
Isolate NodeJS dependent code 

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-node-sdk-js#33] opened 2022-03-09 11:07 UTC
**Task description**
Currently the SDK is not usable outside of nodeJS environments, because the node client uses nodeJS specific libraries, and is everything is exported from the index.

We should restructure the SDK, so that modules reliant on nodeJS is isolated, and the SDK can easily be used in web environments.

**Comment by orhoj** [comment] 2022-04-11 12:42
Closed as a duplicate of https://github.com/Concordium/concordium-node-sdk-js/issues/30.

**Closed by orhoj** 2022-04-11 12:42 UTC
Labels: [Type] Task
